credentials:
  usernames:
    victor:
      email: victor@aberration.com
      name: Victor
      password: $2b$12$.ejUPQtRJR9cLgZd.e7fUeBpUFf5gXT/9RwXsZNCKhvWuT96wsywK
    stephanie:
      email: stephanie@aberration.com
      name: Stephanie
      password: $2b$12$4mstfEdUwlCWJ8r4Zlkd4OfvtMd8Z0MxcOhFrhkLGI4TNQEKjp4sW
    tania:
      email: tania@aberration.com
      name: Tania
      password: $2b$12$0dSKuvytJFaha2dCcrdm6eutW3apTEuwo9sayqVPGim.pTUSaz4K2
cookie:
  expiry_days: 30
  key: nds_signature_key # Must be string
  name: nds_cookie_name
preauthorized:
  emails:
